### ISSUE TITLE
i18n language link text

### ISSUE THREAD

**Issue by techgique** [CDRH/orchid#154]
We discussed a little and think we probably want the link text for switching locale to display as the language's name in the native form to people who speak it. For example, this is how the Wikipedia home page handles language choice: https://www.wikipedia.org/

**Comment by jduss4** [comment]
Seems like we probably just need to add a locales file to orchid (don't need to copy it into apps, I suspect) that has mappings which would then, presumably, be easy to apply per language in the UI:

```
en:
  en: English
  es: Spanish
  yo: Yoruba
es:
  en: Inglés
  es: Español
  yo: Yoruba
yo:
  en: Gẹẹsi
  es: Sipaki
  yo: Yorùbá
```
