### ISSUE TITLE
Separate API default options into tracked file

### ISSUE THREAD

**Issue by jduss4** [CDRH/orchid#53]
Currently, all configuration of options sent to the API on requests are set in `config.yml`, which is gitignored.  This means that any changes we make to say, an app's highlighting or default filters (for example, adding `subcategory|letters` to every request), have to be added to local apps by word of mouth.

At some point, perhaps the following should be pulled into a new file, either overridable or copied into new apps by orchid, etc, and then checked into git.

```
  # API
  api_opts:
    # only grab letters by default
    f:
      - subcategory|Letters

    # sorting and response number
    sort:
      - title|asc
    rows: 50

    # facet info
    facet_limit: 20
    facet_sort: count|desc

    # highlighting
    hl_fl: annotations_text, transcription_t, text
    hl_num: 5
```
